apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/advatys/kubernetes-operators-tools'
    targetRevision: HEAD
    path: olm-helper
    helm:
      values: |

        operatorGroup:
          create: true
          spec:
            targetNamespaces:
            - keycloak-operator
        catalog:
          createCatalog: false
          createCatalogNamespace: false
          name: community-operators
          namespace: openshift-marketplace     
        subscription: 
          package: keycloak-operator
          channel: "fast"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak-operator 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

