{{- range .Values.clients }}
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .name }}
  labels:
    {{- include "keycloak.labels" $. | nindent 4 }}
spec: {{ toYaml .spec | nindent 2 }}

{{- end -}}