---
# The Admin Credentials need to match those used/created by the new Keycloak Operator
apiVersion: v1
kind: Secret
metadata:
  name: credential-{{ .Release.Name }}
type: Opaque
stringData:
  ADMIN_USERNAME: << username >>
  ADMIN_PASSWORD: << password >>
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: credential-{{ .Release.Name }}-patch
spec:
  serviceAccountRef:
    name: keycloak-operator
  patches:
     multiple-namespaced-targets-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        name: credential-{{ .Release.Name }}
      patchTemplate: |
        spec:
          data:
            ADMIN_USERNAME: {{ "{{" }} (index . 1).data.username {{ "}}" }}
            ADMIN_PASSWORD: {{ "{{" }} (index . 1).data.password {{ "}}" }}
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        name: {{ .Release.Name }}-initial-admin
        namespace: {{ .Release.Namespace }}
        fieldPath: $.data
