apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-store
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Release.Namespace }}
      auth:
        serviceAccount:
          name: "keycloak-realm-operator"
---
