{{- range $realm := .Values.realms }}
{{- range $user := $realm.users }}  
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ $user.name }}
  labels:
    app: {{ $.Release.Name }}-{{ $realm.name }}-sso
spec: 
  realmSelector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $realm.name }}-sso
{{ toYaml .spec | nindent 2 }}

{{- end }}
{{- end }}